<a href="https://colab.research.google.com/github/davidzheng66/python3/blob/master/deeplearning/deeplearning-keras-deeplizard-.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#[Prerequisite: Machine Learning and Deep Learning Fundamental - deeplizard](https://www.youtube.com/playlist?list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU)

##[1. Deep Learning Overview & Machine Learning Introduction](https://www.youtube.com/watch?v=gZmobeGL0Yg&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=1)

##[2. Deep Learning](https://www.youtube.com/watch?v=OT1jslLoCyA&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=2)

##[3. Artificial Neural Network (ANN)](https://www.youtube.com/watch?v=hfK_dvC-avg&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=3)

##[4. Layers in a Neural Network](https://www.youtube.com/watch?v=FK77zZxaBoI&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=4)
###Layers in an ANN
Artificial neural network is typically organized in layers. Different types of layers include:
* Dense (or fully connected) Layers
* Convolutional layers
* Pooling Layers
* Recurrent Layers
* Normalization Layers
* Many others


##[5. Activation Functions in a Neural Network](https://www.youtube.com/watch?v=m0pIlLfpXWE&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=5)
###Activation Functions
In an artificial neural network, the activation function of a neuron defines the output of that neuro given a set of inputs.
* Biologically inspired by activity in our brains, where different neurons fire, or are activated, by different stimuli

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation

#Way 1 to create a model
model = Sequential([
    Dense(5, input_shape=(3,), activation='relu')
])

In [ ]:
#Way 2 to create a model
model = Sequential()
model.add(Dense(5, input_shape=(3,)))
model.add(Activation('relu'))

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation

#Way 1 to create a model
model = Sequential([
    Dense(5, input_shape=(3,), activation='relu'),
    Dense(2, activation='softmax')
])

In [ ]:
import numpy as np
# from scipy import ndimage
from scipy import misc
import matplotlib.pyplot as plt
%matplotlib inline

# img = np.expand_dims(ndimage.imread('NN.PNG'), 0)
img = np.expand_dims(misc.imread('NN.PNG'), 0)
plt.imshow(img[0])

##[6. Training a Neural Network](https://www.youtube.com/watch?v=sZAlS3_dnk0&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=6)

###Training
Solving an optimization proble
* Optimizing weights
 * with Stochastic Gradient Descent (SGD)
* Objective: Minimize the loss function

###Learning


##[7. How a Neural Network Learns](https://www.youtube.com/watch?v=_N5kpSMDf4o&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=7)

##[8. Loss in a Neural Network](https://www.youtube.com/watch?v=Skc8nqJirJg&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=8)

##[9. Learning Rate in a Neural Network](https://www.youtube.com/watch?v=jWT-AX9677k&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=9)

##[10. Train, Test & Validation Sets](https://www.youtube.com/watch?v=Zi-0rlM4RDs&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=10)

##[11. Predicting with a Neural Network](https://www.youtube.com/watch?v=Z0KVRdE_a7Q&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=11)

##[12. Overfitting in a Neural Network](https://www.youtube.com/watch?v=DEMmkFC6IGM&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=12)

##[13. Underfitting in a Neural Network](https://www.youtube.com/watch?v=0h8lAm5Ki5g&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=13)

##[14. Supervised Learning](https://www.youtube.com/watch?v=Quh6x4kG6VY&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=14)

##[15. Unsupervised Learning](https://www.youtube.com/watch?v=lEfrr0Yr684&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=15)

##[16. Semi-supervised Learning](https://www.youtube.com/watch?v=b-yhKUINb7o&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=16)

##[17. Data Augmentation](https://www.youtube.com/watch?v=rfM4DaLTkMs&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=17)

##[18. One-hot Encoding](https://www.youtube.com/watch?v=v_4KWmkwmsU&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=18)

##[19. Convolutional Neural Networks](https://www.youtube.com/watch?v=YRhxdVk_sIs&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=19)

##[20. Visualizing Convolutional Filters from a CNN](https://www.youtube.com/watch?v=cNBBNAxC8l4&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=20)

##[21. Zero Padding in Convolutional Neural Networks](https://www.youtube.com/watch?v=qSTv_m-KFk0&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=21)

##[22. Max Pooling in Convolutional Neural Networks](https://www.youtube.com/watch?v=ZjM_XQa5s6s&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=22)

##[23. Backpropagation | Part 1 - The Intuition](https://www.youtube.com/watch?v=XE3krf3CQls&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=23)

##[24. Backpropagation | Part 2 - The Mathematical Notation](https://www.youtube.com/watch?v=2mSysRx-1c0&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=24)

##[25. Backpropagation | Part 3 - Mathematical Observations](https://www.youtube.com/watch?v=G5b4jRBKNxw&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=25)

##[26. Backpropagation | Part 4 - Calculating the Gradient](https://www.youtube.com/watch?v=Zr5viAZGndE&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=26)

##[27. Backpropagation | Part 5 - What Puts the "back" in Backprop?](https://www.youtube.com/watch?v=xClK__CqZnQ&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=27)

##[28. Vanishing & Exploding Gradient | A Problem Resulting from Backprogagation](https://www.youtube.com/watch?v=qO_NLVjD6zE&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=28)
- Gradient: referrring to the gradient of the loss function with respect to the weights in the network

##[29. Weight Initialization | A Way to Reduce the Vanishing Gradient Problem](https://www.youtube.com/watch?v=8krd5qKVw-Q&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=29)

##[30. Bias in an Artificial Neural Network | How Bias Impacts Training](https://www.youtube.com/watch?v=HetFihsXSys&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=30)

##[31. Learnable Parameters in an Artificial Neural Network](https://www.youtube.com/watch?v=pg3hJpSopHQ&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=31)

##[32. Learnable Parameters in a Convolutional Neural Network (CNN)](https://www.youtube.com/watch?v=gmBfb6LNnZs&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=32)

##[33. Regularization in a Neural Network](https://www.youtube.com/watch?v=iuJgyiS7BKM&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=33)

##[34. Batch Size in a Neural Network](https://www.youtube.com/watch?v=U4WB9p6ODjM&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=34)

##[35. Fine-tuning a Neural Network](https://www.youtube.com/watch?v=5T-iXNNiwIs&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=35)

##[36. Batch Normalization ("batch norm")](https://www.youtube.com/watch?v=dXB-KQYkzNU&list=PLZbbT5o_s2xq7LwI2y8_QtvuXZedL6tQU&index=36)

#[Keras with TensorFlow Course - Python Deep Learning and Neural Networks for Beginners Tutorial](https://www.youtube.com/watch?v=qFJeN9V1ZsI&t=94s)
- ⌨️ (00:00:00) Welcome to this course
- ⌨️ (00:00:16) Keras Course Introduction
- ⌨️ (00:00:50) Course Prerequisites
- ⌨️ (00:01:33) DEEPLIZARD Deep Learning Path
- ⌨️ (00:01:45) Course Resources
- ⌨️ (00:02:30) About Keras
- ⌨️ (00:06:41) Keras with TensorFlow - Data Processing for Neural Network Training
- ⌨️ (00:18:39) Create an Artificial Neural Network with TensorFlow's Keras API
- ⌨️ (00:24:36) Train an Artificial Neural Network with TensorFlow's Keras API
- ⌨️ (00:30:07) Build a Validation Set With TensorFlow's Keras API
- ⌨️ (00:39:28) Neural Network Predictions with TensorFlow's Keras API
- ⌨️ (00:47:48) Create a Confusion Matrix for Neural Network Predictions
- ⌨️ (00:52:29) Save and Load a Model with TensorFlow's Keras API
- ⌨️ (01:01:25) Image Preparation for CNNs with TensorFlow's Keras API
- ⌨️ (01:19:22) Build and Train a CNN with TensorFlow's Keras API
- ⌨️ (01:28:42) CNN Predictions with TensorFlow's Keras API
- ⌨️ (01:37:05) Build a Fine-Tuned Neural Network with TensorFlow's Keras API
- ⌨️ (01:48:19) Train a Fine-Tuned Neural Network with TensorFlow's Keras API
- ⌨️ (01:52:39) Predict with a Fine-Tuned Neural Network with TensorFlow's Keras API
- ⌨️ (01:57:50) MobileNet Image Classification with TensorFlow's Keras API
- ⌨️ (02:11:18) Process Images for Fine-Tuned MobileNet with TensorFlow's Keras API
- ⌨️ (02:24:24) Fine-Tuning MobileNet on Custom Data Set with TensorFlow's Keras API
- ⌨️ (02:38:59) Data Augmentation with TensorFlow' Keras API
- ⌨️ (02:47:24) Collective Intelligence and the DEEPLIZARD HIVEMIND

##[Keras](https://keras.io/)

##Data Preparation and Processing

In [1]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

###Example data:
- An experiemental drug was tested on individuals from ages 13 to 100 in a clinical trial.
- The trial has 2100 participants. Half were under 65 years old, half were 65 years older.
- Around 95% of patients 65 or older experienced side effects.
- Around 95% of patients under 65 experienced no side effects.

In [27]:
train_labels = []
train_samples = []

for i in range(50):
  # The ~5% of younger individuals who did experience side effects
  random_younger = randint(13, 64)
  train_samples.append(random_younger)
  train_labels.append(1)

  # The ~5% of older individuals who did not experience side effects
  random_older = randint(65, 100)
  train_samples.append(random_older)
  train_labels.append(0)

for i in range(1000):
  # The ~95% of younger individuals who did not experience side effects
  random_younger = randint(13, 64)
  train_samples.append(random_younger)
  train_labels.append(0)

  # The ~95% of older individuals who did experience side effects
  random_older = randint(65, 100)
  train_samples.append(random_older)
  train_labels.append(1)

In [28]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels, train_samples = shuffle(train_labels, train_samples)

print(train_labels)
print(train_samples)

[1 0 1 ... 1 0 1]
[97 56 84 ... 74 58 81]


In [29]:
scaler = MinMaxScaler(feature_range=(0,1))
print(scaler)
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))
print(scaled_train_samples)

MinMaxScaler(copy=True, feature_range=(0, 1))
[[0.96551724]
 [0.49425287]
 [0.81609195]
 ...
 [0.70114943]
 [0.51724138]
 [0.7816092 ]]


##Create an Artificial Neural Network with TensorFlow's Keras API 
###Simple tf.keras Sequential Model

In [30]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [16]:
physical_devices = tf.config.experimental.list_physical_devices('GPU')
print('Num GPUs Available: ', len(physical_devices))
tf.config.experimental.set_memory_growth(physical_devices[0], True)

Num GPUs Available:  0


IndexError: ignored

In [31]:
model = Sequential([
    Dense(units=16, input_shape=(1,), activation='relu'),
    Dense(units=32, activation='relu'),
    Dense(units=2, activation='softmax')
])

In [32]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_7 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_8 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


## Train an Artificial Neural Network with TensorFlow's Keras API

In [26]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x=scaled_train_samples, y=train_labels, batch_size=10, epochs=30, shuffle=True, verbose=2)

Epoch 1/30
210/210 - 0s - loss: 0.2330 - accuracy: 0.9524
Epoch 2/30
210/210 - 0s - loss: 0.2330 - accuracy: 0.9505
Epoch 3/30
210/210 - 0s - loss: 0.2328 - accuracy: 0.9514
Epoch 4/30
210/210 - 0s - loss: 0.2328 - accuracy: 0.9524
Epoch 5/30
210/210 - 0s - loss: 0.2327 - accuracy: 0.9524
Epoch 6/30
210/210 - 0s - loss: 0.2327 - accuracy: 0.9524
Epoch 7/30
210/210 - 0s - loss: 0.2325 - accuracy: 0.9524
Epoch 8/30
210/210 - 0s - loss: 0.2324 - accuracy: 0.9524
Epoch 9/30
210/210 - 0s - loss: 0.2323 - accuracy: 0.9524
Epoch 10/30
210/210 - 0s - loss: 0.2322 - accuracy: 0.9490
Epoch 11/30
210/210 - 0s - loss: 0.2321 - accuracy: 0.9524
Epoch 12/30
210/210 - 0s - loss: 0.2320 - accuracy: 0.9524
Epoch 13/30
210/210 - 0s - loss: 0.2320 - accuracy: 0.9524
Epoch 14/30
210/210 - 0s - loss: 0.2318 - accuracy: 0.9524
Epoch 15/30
210/210 - 0s - loss: 0.2319 - accuracy: 0.9524
Epoch 16/30
210/210 - 0s - loss: 0.2317 - accuracy: 0.9524
Epoch 17/30
210/210 - 0s - loss: 0.2317 - accuracy: 0.9524
Epoch 

##Build a Validation Set With TensorFlow's Keras API

In [34]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x=scaled_train_samples, y=train_labels, validation_split=0.1, batch_size=10, epochs=30, shuffle=True, verbose=2)

Epoch 1/30
189/189 - 1s - loss: 0.2704 - accuracy: 0.9381 - val_loss: 0.2932 - val_accuracy: 0.9286
Epoch 2/30
189/189 - 0s - loss: 0.2688 - accuracy: 0.9365 - val_loss: 0.2912 - val_accuracy: 0.9286
Epoch 3/30
189/189 - 0s - loss: 0.2674 - accuracy: 0.9418 - val_loss: 0.2908 - val_accuracy: 0.9143
Epoch 4/30
189/189 - 0s - loss: 0.2659 - accuracy: 0.9434 - val_loss: 0.2896 - val_accuracy: 0.9143
Epoch 5/30
189/189 - 0s - loss: 0.2650 - accuracy: 0.9386 - val_loss: 0.2879 - val_accuracy: 0.9286
Epoch 6/30
189/189 - 0s - loss: 0.2639 - accuracy: 0.9407 - val_loss: 0.2864 - val_accuracy: 0.9286
Epoch 7/30
189/189 - 0s - loss: 0.2630 - accuracy: 0.9429 - val_loss: 0.2857 - val_accuracy: 0.9286
Epoch 8/30
189/189 - 0s - loss: 0.2620 - accuracy: 0.9413 - val_loss: 0.2844 - val_accuracy: 0.9286
Epoch 9/30
189/189 - 0s - loss: 0.2611 - accuracy: 0.9444 - val_loss: 0.2841 - val_accuracy: 0.9286
Epoch 10/30
189/189 - 0s - loss: 0.2605 - accuracy: 0.9439 - val_loss: 0.2833 - val_accuracy: 0.9286

##Neural Network Predictions

In [35]:
test_labels = []
test_samples = []

for i in range(10):
  # The ~5% of younger individuals who did experience side effects
  random_younger = randint(13, 64)
  test_samples.append(random_younger)
  test_labels.append(1)

  # The ~5% of older individuals who did not experience side effects
  random_older = randint(65, 100)
  test_samples.append(random_older)
  test_labels.append(0)

for i in range(200):
  # The ~95% of younger individuals who did not experience side effects
  random_younger = randint(13, 64)
  test_samples.append(random_younger)
  test_labels.append(0)

  # The ~95% of older individuals who did experience side effects
  random_older = randint(65, 100)
  test_samples.append(random_older)
  test_labels.append(1)

In [36]:
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)
test_labels, test_samples = shuffle(test_labels, test_samples)

print(test_labels)
print(test_samples)

[0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 1 1 1 1 1 0
 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 0 1 1 0 0 1
 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 1 0 1
 0 1 1 1 0 1 0 0 1 1 1 1 0 0 0 1 1 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 1 0 1 1
 1 0 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 0 1 1
 1 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 1 0 1 1 0 1 0
 0 1 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 0 0 1 1 0 0 1 1 0 0
 0 0 1 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0
 0 1 0 1 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 0 0 0 0 0 0 1 1 1
 1 1 1 0 0 0 1 0 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 1 0 0 1 1 1
 0 1 0 1 1 0 0 1 0 0 1 0 1]
[ 18  84  50  60  43  26  33  48  55  62  66  39  51  36  35  70  25  57
  58  25  87  78  16  17  67  31  86  90  82  31  26  84  92  89  85  86
 

In [38]:
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))
print(scaled_test_samples)

[[0.05747126]
 [0.81609195]
 [0.42528736]
 [0.54022989]
 [0.34482759]
 [0.14942529]
 [0.22988506]
 [0.40229885]
 [0.48275862]
 [0.56321839]
 [0.6091954 ]
 [0.29885057]
 [0.43678161]
 [0.26436782]
 [0.25287356]
 [0.65517241]
 [0.13793103]
 [0.50574713]
 [0.51724138]
 [0.13793103]
 [0.85057471]
 [0.74712644]
 [0.03448276]
 [0.04597701]
 [0.62068966]
 [0.20689655]
 [0.83908046]
 [0.88505747]
 [0.79310345]
 [0.20689655]
 [0.14942529]
 [0.81609195]
 [0.90804598]
 [0.87356322]
 [0.82758621]
 [0.83908046]
 [0.47126437]
 [0.06896552]
 [0.11494253]
 [0.02298851]
 [0.22988506]
 [0.67816092]
 [0.20689655]
 [0.12643678]
 [0.85057471]
 [0.72413793]
 [0.70114943]
 [0.93103448]
 [0.90804598]
 [0.42528736]
 [0.81609195]
 [0.14942529]
 [0.63218391]
 [0.2183908 ]
 [0.57471264]
 [0.95402299]
 [0.75862069]
 [0.64367816]
 [0.66666667]
 [0.90804598]
 [0.74712644]
 [0.36781609]
 [0.10344828]
 [0.05747126]
 [0.52873563]
 [0.42528736]
 [0.03448276]
 [0.83908046]
 [0.91954023]
 [0.75862069]
 [0.79310345]
 [0.39

In [41]:
predictions = model.predict(x=scaled_test_samples, batch_size=10, verbose=0)
print(predictions.shape)
print(predictions)

(420, 2)
[[0.97432363 0.02567634]
 [0.0555435  0.9444565 ]
 [0.9166857  0.08331436]
 [0.6631673  0.3368327 ]
 [0.95384926 0.04615078]
 [0.9725893  0.02741066]
 [0.9699461  0.03005392]
 [0.93161637 0.06838365]
 [0.8273128  0.17268714]
 [0.57974726 0.42025274]
 [0.40379623 0.59620374]
 [0.96309984 0.0369002 ]
 [0.9061441  0.09385588]
 [0.96695584 0.03304411]
 [0.9681525  0.03184744]
 [0.24953742 0.7504626 ]
 [0.9728122  0.0271878 ]
 [0.77047527 0.22952472]
 [0.7375252  0.2624748 ]
 [0.9728122  0.0271878 ]
 [0.04253287 0.95746714]
 [0.09344301 0.906557  ]
 [0.97474027 0.02525972]
 [0.97453284 0.0254672 ]
 [0.3618084  0.6381916 ]
 [0.97114843 0.02885155]
 [0.04650871 0.9534912 ]
 [0.03246514 0.9675348 ]
 [0.06621147 0.93378854]
 [0.97114843 0.02885155]
 [0.9725893  0.02741066]
 [0.0555435  0.9444565 ]
 [0.0270767  0.9729233 ]
 [0.0355348  0.9644652 ]
 [0.05083647 0.94916356]
 [0.04650871 0.9534912 ]
 [0.8512645  0.1487355 ]
 [0.97411287 0.02588714]
 [0.9732527  0.02674733]
 [0.97494614 0.0

In [44]:
rounded_predictions = np.argmax(predictions, axis=1)
print(rounded_predictions.shape)
print(rounded_predictions)

(420,)
[0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 1 1 0 0 1 1 1 1 1 0
 0 0 0 0 1 0 0 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1
 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 1 0 1
 0 1 1 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 1 1 1 1
 1 0 0 0 1 1 1 1 1 1 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 0 1 1
 1 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 1 0 1 1 0 1 0
 0 1 0 0 1 0 1 1 1 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 0 0 1 1 0 0
 0 0 1 1 0 1 0 1 1 0 0 1 1 1 0 0 1 0 1 1 1 0 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0
 0 1 0 1 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 0 0 0 0 0 0 1 1 1
 1 1 1 0 0 0 1 0 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1 0 1 1 1
 1 1 0 1 1 0 0 0 0 0 1 0 1]


#[Practical Machine Learning Tutorial with Python -  sentdex](https://www.youtube.com/watch?v=OGxgnH8y2NM&list=PLQVvvaa0QuDfKTOs3Keq_kaG2P55YRn5v)

##Install Packages
- ```pip install sklean```
- ```pip install quandl```
- ```pip isntall pandas```


#[Deep Learning - 3Blue1Brown](https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi)

#[Practical Deep Learning for Coders - Full Course from fast.ai and Jeremy Howard](https://www.youtube.com/watch?v=0oyCUWLL_fU&list=RDCMUC8butISFwT-Wl7EV0hUK0BQ&start_radio=1&t=55)

#[Python for Data Science](https://www.youtube.com/watch?v=LHBE6Q9XlzI&t=40900s)

#[Learn Data Science Tutorial - Full Course for Beginners](https://www.youtube.com/watch?v=ua-CiDNNj30)