<a href="https://colab.research.google.com/github/davidzheng66/python3/blob/master/deeplearning/practical-machine-learning-sentdex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#[Practical Machine Learning Tutorial with Python -  sentdex](https://www.youtube.com/watch?v=OGxgnH8y2NM&list=PLQVvvaa0QuDfKTOs3Keq_kaG2P55YRn5v)

##[1. Python Introduction ](https://www.youtube.com/watch?v=OGxgnH8y2NM&list=PLQVvvaa0QuDfKTOs3Keq_kaG2P55YRn5v&index=1)
###What you will need for this tutorial series:
Install numpy, matplotlib, pandas, sklearn and their dependencies
```
- pip install sklearn
- pip install quandl
- pip install pandas
- pip install numpy
- pip install scipy
- pip install scikit-learn
- pip install matplotlib
```

##[2. Regression Introduction](https://www.youtube.com/watch?v=JcI5Vnw0b2c&list=PLQVvvaa0QuDfKTOs3Keq_kaG2P55YRn5v&index=2)

In [24]:
!pip install sklearn
!pip install quandl

###[quandl](https://www.quandl.com/tools/full-list)

In [ ]:
# !pip list

In [26]:
import pandas as pd
import quandl, math
import numpy as np
from sklearn import preprocessing, svm #cross_validation
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [27]:
quandl.ApiConfig.api_key =  'agNNnvSVprb22QD7mA8L'
df = quandl.get('WIKI/GOOGL') # https://www.quandl.com/tools/python

In [28]:
print(df.head())

              Open    High     Low  ...   Adj. Low  Adj. Close  Adj. Volume
Date                                ...                                    
2004-08-19  100.01  104.06   95.96  ...  48.128568   50.322842   44659000.0
2004-08-20  101.01  109.08  100.50  ...  50.405597   54.322689   22834300.0
2004-08-23  110.76  113.48  109.05  ...  54.693835   54.869377   18256100.0
2004-08-24  111.24  111.60  103.57  ...  51.945350   52.597363   15247300.0
2004-08-25  104.76  108.00  103.88  ...  52.100830   53.164113    9188600.0

[5 rows x 12 columns]


In [29]:
df = df[['Adj. Open', 'Adj. High', 'Adj. Low', 'Adj. Close', 'Adj. Volume',]]
print(df.head())

            Adj. Open  Adj. High   Adj. Low  Adj. Close  Adj. Volume
Date                                                                
2004-08-19  50.159839  52.191109  48.128568   50.322842   44659000.0
2004-08-20  50.661387  54.708881  50.405597   54.322689   22834300.0
2004-08-23  55.551482  56.915693  54.693835   54.869377   18256100.0
2004-08-24  55.792225  55.972783  51.945350   52.597363   15247300.0
2004-08-25  52.542193  54.167209  52.100830   53.164113    9188600.0


In [30]:
df['HL_PCT'] = (df['Adj. High'] - df['Adj. Close']) / df['Adj. Close'] * 100.0
print(df['HL_PCT'].head())
print(df.head())

Date
2004-08-19    3.712563
2004-08-20    0.710922
2004-08-23    3.729433
2004-08-24    6.417469
2004-08-25    1.886792
Name: HL_PCT, dtype: float64
            Adj. Open  Adj. High   Adj. Low  Adj. Close  Adj. Volume    HL_PCT
Date                                                                          
2004-08-19  50.159839  52.191109  48.128568   50.322842   44659000.0  3.712563
2004-08-20  50.661387  54.708881  50.405597   54.322689   22834300.0  0.710922
2004-08-23  55.551482  56.915693  54.693835   54.869377   18256100.0  3.729433
2004-08-24  55.792225  55.972783  51.945350   52.597363   15247300.0  6.417469
2004-08-25  52.542193  54.167209  52.100830   53.164113    9188600.0  1.886792


In [31]:
df['PCT_change'] = (df['Adj. Close'] - df['Adj. Open']) / df['Adj. Open'] * 100.0
print(df['PCT_change'].head())
print(df)

Date
2004-08-19    0.324968
2004-08-20    7.227007
2004-08-23   -1.227880
2004-08-24   -5.726357
2004-08-25    1.183658
Name: PCT_change, dtype: float64
              Adj. Open    Adj. High  ...    HL_PCT  PCT_change
Date                                  ...                      
2004-08-19    50.159839    52.191109  ...  3.712563    0.324968
2004-08-20    50.661387    54.708881  ...  0.710922    7.227007
2004-08-23    55.551482    56.915693  ...  3.729433   -1.227880
2004-08-24    55.792225    55.972783  ...  6.417469   -5.726357
2004-08-25    52.542193    54.167209  ...  1.886792    1.183658
...                 ...          ...  ...       ...         ...
2018-03-21  1092.570000  1108.700000  ...  1.343693    0.130884
2018-03-22  1080.010000  1083.920000  ...  2.921711   -2.487014
2018-03-23  1051.370000  1066.780000  ...  3.918952   -2.360729
2018-03-26  1050.600000  1059.270000  ...  0.491419    0.332191
2018-03-27  1063.900000  1064.540000  ...  5.720301   -5.353887

[3424 rows x 7

In [32]:
df = df[['Adj. Close', 'HL_PCT', 'PCT_change', 'Adj. Volume']]
print(df)

             Adj. Close    HL_PCT  PCT_change  Adj. Volume
Date                                                      
2004-08-19    50.322842  3.712563    0.324968   44659000.0
2004-08-20    54.322689  0.710922    7.227007   22834300.0
2004-08-23    54.869377  3.729433   -1.227880   18256100.0
2004-08-24    52.597363  6.417469   -5.726357   15247300.0
2004-08-25    53.164113  1.886792    1.183658    9188600.0
...                 ...       ...         ...          ...
2018-03-21  1094.000000  1.343693    0.130884    1990515.0
2018-03-22  1053.150000  2.921711   -2.487014    3418154.0
2018-03-23  1026.550000  3.918952   -2.360729    2413517.0
2018-03-26  1054.090000  0.491419    0.332191    3272409.0
2018-03-27  1006.940000  5.720301   -5.353887    2940957.0

[3424 rows x 4 columns]


In [33]:
df1= df[['Adj. Close']]
print(df1)
type(df1)

             Adj. Close
Date                   
2004-08-19    50.322842
2004-08-20    54.322689
2004-08-23    54.869377
2004-08-24    52.597363
2004-08-25    53.164113
...                 ...
2018-03-21  1094.000000
2018-03-22  1053.150000
2018-03-23  1026.550000
2018-03-26  1054.090000
2018-03-27  1006.940000

[3424 rows x 1 columns]


pandas.core.frame.DataFrame

In [34]:
df2= df['Adj. Close']
print(df2)
type(df2)

Date
2004-08-19      50.322842
2004-08-20      54.322689
2004-08-23      54.869377
2004-08-24      52.597363
2004-08-25      53.164113
                 ...     
2018-03-21    1094.000000
2018-03-22    1053.150000
2018-03-23    1026.550000
2018-03-26    1054.090000
2018-03-27    1006.940000
Name: Adj. Close, Length: 3424, dtype: float64


pandas.core.series.Series

##[3. Regression Features and Labels](https://www.youtube.com/watch?v=lN5jesocJjk&list=PLQVvvaa0QuDfKTOs3Keq_kaG2P55YRn5v&index=3)

In [35]:
forecast_col = 'Adj. Close'
df.fillna(-99999, inplace=True)

forecast_out = int(math.ceil(0.01 * len(df)))
print(forecast_out)

35


In [36]:
df['label'] = df[forecast_col].shift(-forecast_out)
print(df['label'])
print(df)

Date
2004-08-19    69.078238
2004-08-20    67.839414
2004-08-23    68.912727
2004-08-24    70.668146
2004-08-25    71.219849
                ...    
2018-03-21          NaN
2018-03-22          NaN
2018-03-23          NaN
2018-03-26          NaN
2018-03-27          NaN
Name: label, Length: 3424, dtype: float64
             Adj. Close    HL_PCT  PCT_change  Adj. Volume      label
Date                                                                 
2004-08-19    50.322842  3.712563    0.324968   44659000.0  69.078238
2004-08-20    54.322689  0.710922    7.227007   22834300.0  67.839414
2004-08-23    54.869377  3.729433   -1.227880   18256100.0  68.912727
2004-08-24    52.597363  6.417469   -5.726357   15247300.0  70.668146
2004-08-25    53.164113  1.886792    1.183658    9188600.0  71.219849
...                 ...       ...         ...          ...        ...
2018-03-21  1094.000000  1.343693    0.130884    1990515.0        NaN
2018-03-22  1053.150000  2.921711   -2.487014    3418154.0 

In [37]:
df.dropna(inplace=True)
print(df.tail())

            Adj. Close    HL_PCT  PCT_change  Adj. Volume    label
Date                                                              
2018-01-30     1177.37  0.896914   -0.029718    1792602.0  1094.00
2018-01-31     1182.22  0.346805   -0.134312    1643877.0  1053.15
2018-02-01     1181.59  0.495942    0.476195    2774967.0  1026.55
2018-02-02     1119.20  1.081129   -0.729098    5798880.0  1054.09
2018-02-05     1068.76  4.325574   -2.893850    3742469.0  1006.94


In [38]:
print(df.head())

            Adj. Close    HL_PCT  PCT_change  Adj. Volume      label
Date                                                                
2004-08-19   50.322842  3.712563    0.324968   44659000.0  69.078238
2004-08-20   54.322689  0.710922    7.227007   22834300.0  67.839414
2004-08-23   54.869377  3.729433   -1.227880   18256100.0  68.912727
2004-08-24   52.597363  6.417469   -5.726357   15247300.0  70.668146
2004-08-25   53.164113  1.886792    1.183658    9188600.0  71.219849


##[4. Regression Training and Testing](https://www.youtube.com/watch?v=r4mwkS2T9aI&list=PLQVvvaa0QuDfKTOs3Keq_kaG2P55YRn5v&index=4)

In [46]:
X = np.array(df.drop(['label'], 1))
print(X)
y = np.array(df['label'])
print(y)
X = preprocessing.scale(X)
print(X)

[[ 5.03228418e+01  3.71256291e+00  3.24967503e-01  4.46590000e+07]
 [ 5.43226889e+01  7.10922353e-01  7.22700723e+00  2.28343000e+07]
 [ 5.48693765e+01  3.72943327e+00 -1.22788010e+00  1.82561000e+07]
 ...
 [ 1.18159000e+03  4.95941909e-01  4.76194525e-01  2.77496700e+06]
 [ 1.11920000e+03  1.08112938e+00 -7.29098295e-01  5.79888000e+06]
 [ 1.06876000e+03  4.32557356e+00 -2.89384977e+00  3.74246900e+06]]
[  69.0782379    67.83941377   68.91272699 ... 1026.55       1054.09
 1006.94      ]
[[-1.41006544  2.35025798  0.23194449  4.44790502]
 [-1.39402696 -0.30866295  4.84146176  1.80881376]
 [-1.39183486  2.36520212 -0.80512254  1.25520764]
 ...
 [ 3.12606095 -0.49909747  0.33294124 -0.61680539]
 [ 2.87589111  0.01927479 -0.47201183 -0.25114711]
 [ 2.67363808  2.89327664 -1.91773798 -0.4998129 ]]


In [48]:
# X = X[:-forecast_out + 1]
# print(X)
# df.dropna(inplace=True)
y = np.array(df['label'])
print(len(X), len(y))

3389 3389


In [ ]:
# !pip install scikit-learn==0.20
# pip install -U scikit-learn

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
clf = LinearRegression(n_jobs=10)
clf.fit(X_train, y_train)

accuracy = clf.score(X_test, y_test)
print(accuracy)

0.9797437478518206


In [61]:
# clf = svm.SVR(kernel='poly')
# clf.fit(X_train, y_train)

# accuracy = clf.score(X_test, y_test)
# print(accuracy)

0.622181001388604


#[Deep Learning - 3Blue1Brown](https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi)

#[Practical Deep Learning for Coders - Full Course from fast.ai and Jeremy Howard](https://www.youtube.com/watch?v=0oyCUWLL_fU&list=RDCMUC8butISFwT-Wl7EV0hUK0BQ&start_radio=1&t=55)