<a href="https://colab.research.google.com/github/davidzheng66/python3/blob/master/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#[Numpy](https://numpy.org/)
#[Python Numpy Tutorial for Beginners](https://www.youtube.com/watch?v=QUT1VHiLmmI)
#[Introduction to Numerical Computing with NumPy: Alex Chabot-Leclerc](https://www.youtube.com/watch?v=ZB7BZMhfPgk&feature=youtu.be)

In [8]:
import numpy as np

In [21]:
stats = np.array([[1,2,3], [4,5,6], [7,8,9]])
stats
print(stats)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
np.min(stats, axis=1)

array([1, 4, 7])